### ISSUE TITLE
Colour Option - Admin/Teacher

### ISSUE THREAD

**Issue by jtyronian** [dbnschools/moodle-theme_learnr#18]
In Fordson there was a colour option setting so that if you had elevated permissions as a site Admin OR a teacher within a course, the top bar (where site name, Home, Dashboard etc sit), is it possible to add that in this theme and possible expanding so a site admin can be set as 1 colour and someone with permissions on a category or course has another and anyone else i.e. student would be the default/base colour?

**Comment by dbnschools** [comment]
Excellent idea.  This is a feature that we have not considered bringing over since we ended up not using it.  It created a bit of confusion unless the user was told what the colors meant.  Our intent is to make it as intuitive as possible.  A teacher or student might be confused as to why they have different colors.

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union. I have discontinued the development of this fork. All new releases will be as a proper child theme to Boost Union under the same name. I am closing this issue since the newest version will not have the same issues. The latest release posted here is a child theme now.
