### ISSUE TITLE
Text color of Log in

### ISSUE THREAD

**Issue by beffad** [dbnschools/moodle-theme_learnr#3]
Hello,
Is it possible to change the color of the text "Log in" in the home page ? I have blue on blue...

Best regards,
Daniel Beffa
![2022-05-14_08-50-55](https://user-images.githubusercontent.com/10848267/168414526-092a3fb4-fec3-4a3b-9c1b-ef2cfac590d4.jpg)
a

**Comment by Ruanc66** [comment]
Hi,

I have the same issue. This makes it impossible to see the login button. 

It seems to match the colour that you choose as the background colour as mine is purple on purple until you hover over it.

Regards
Ruan

**Comment by dbnschools** [comment]
This will be a fairly simple css fix in the next release.

**Comment by Ruanc66** [comment]
I am so out of practice with working with the CSS. Can anyone please give me an example of how I should write the CSS in the to change the color of the login text color until the update comes out so that I can insert it into the custom CSS field? 

I am struggling with the dropdown icon color as well so this is what I tried to write for it:
`# user-menu-toggle {
color: #55effa;
}`

This is obviously wrong as it has no effect so any help will be appreciated.

Regards
Ruan

**Comment by dbnschools** [comment]
Fixed in 1.6 release
