### ISSUE TITLE
scrollspy issue

### ISSUE THREAD

**Issue by carlosjac** [dbnschools/moodle-theme_learnr#31]
Hi

If scrollspy is set to yes, my/courses.php fails to show the list of courses.
Setting scrollspy to No, my/courses.php works fine

Moodle 4.2
LearnR v4.2.r7

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.

**Comment by dbnschools** [comment]
This could be a javascript conflict with another plugin you have on your site.
