### ISSUE TITLE
how to install mont serrat and google fonts 5?

### ISSUE THREAD

**Issue by ghost** [dbnschools/moodle-theme_learnr#33]
guys, sorry if it is not the best place to ask for support, but, no idea about where to do it.
i would like to install new fonts on learnR moodle theme, such as mont serrat, and, i don't know how to do it.
and i downt know how to install google fonts latest versions.
can someone, in god's name, explain, on a full tutorial, about how to download, install google fonts and mont serrat?
thanks

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
