### ISSUE TITLE
showcourseindexnav toggle in website administration

### ISSUE THREAD

**Issue by wwobble** [dbnschools/moodle-theme_learnr#37]
When I use the toggle for showing or hiding the course index navigation it toggles two things:
1) the course index navigation on the left side 
2) the block drawer on the right side

I want to disable the course index on the left and enable the block drawer on the right side. I think there is a toggle missing. In the last version I could toggle them independently. 
If I disable the toggle for the course index on the left the blocks on the right show up inside the content wrapper so the content shrinks which I would like to avoid.

Thank you

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
