### ISSUE TITLE
Impossible to create a group in a course

### ISSUE THREAD

**Issue by MFBrice** [dbnschools/moodle-theme_learnr#39]
When creating a group in a course, the creation/modification menus, the list of groups and the group creation window do not appear.
After checking when passing the course in another theme, the window appears correctly  and the creation of a group is then possible.

Can you tell me if this is a theme bug?
Moodle version : 4.1.4+
Theme version : V4.2.r8

![Group Bug LearnR](https://github.com/dbnschools/moodle-theme_learnr/assets/144250024/1c522d23-34ec-4d30-8dd1-3e5119ee1915)
![Group constitution Boost](https://github.com/dbnschools/moodle-theme_learnr/assets/144250024/5aff65fc-6a46-4725-8df0-d01ae2a94fb3)

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
