### ISSUE TITLE
Too much data passed as arguments to js_call_amd("core/showhidesettings", "init").

### ISSUE THREAD

**Issue by caiadogithub** [dbnschools/moodle-theme_learnr#40]
Hi,

When accessing "/admin/settings.php?section=theme_learnr_content" I got the following error message:

"Too much data passed as arguments to js_call_amd("core/showhidesettings", "init"). Generally there are better ways to pass lots of data from PHP to JavaScript, for example via Ajax, data attributes, ... . This warning is triggered if the argument string becomes longer than 1024 characters.

    line 1066 of /lib/outputrequirementslib.php: call to debugging()
    line 173 of /admin/settings.php: call to page_requirements_manager->js_call_amd()"

Ricardo

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
