### ISSUE TITLE
Bulk Actions - Footer doesnt pop up

### ISSUE THREAD

**Issue by glennarcher-nz** [dbnschools/moodle-theme_learnr#45]
Moodle 4.3 added bulk actions when clicking on it an additional menu should display in the footer area like this

![image](https://github.com/dbnschools/moodle-theme_learnr/assets/19960965/db5bc516-0295-49d2-b31e-95b7d0d862de)

However when the theme is switched to LearnR it does not appear

Any advice on enabling it?

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union.  I have discontinued the development of this fork.  All new releases will be as a proper child theme to Boost Union under the same name.  I am closing this issue since the newest version will not have the same issues.  The latest release posted here is a child theme now.
