### ISSUE TITLE
Course tile

### ISSUE THREAD

**Issue by Nenuial** [dbnschools/moodle-theme_learnr#49]
I'm currently trying to update my Moodle to 4.4 (I am aware that LearnR is currently not yet supporting that version). I have followed the update advice by uninstalling the LearnR plugin, reinstalling Boost Union and LearnR and it works as expected.

The only thing I am missing is the course tile style (setting _coursetilestyle_) which I can't find anymore. Is this because I'm using LearnR with Moodle 4.4, or is this setting going away ?

**Comment by dbnschools** [comment]
We took out the Moodle Course tile option because it looked like there was work being done in Boost Union that would have conflicted with this feature.  I took it out but now it appears that course tile feature has stalled with Boost Union.  I am waiting to see if they just decide to not implement it at all.
