### ISSUE TITLE
Search Icon after click hides other menu items in Top menu and no way back

### ISSUE THREAD

**Issue by lisandi** [dbnschools/moodle-theme_learnr#9]
When you click the search icon in the top bar you get immediately directed to the search field (but that itself is pretty small) and all other menu items disappear in the top bar.

And there is no way back - if you don't enter anything in search and like to cancel the search you have no way to click the other top menu items - only workaround is to reload the complete page
![Screen Shot 2022-06-21 at 19 20 28](https://user-images.githubusercontent.com/1982011/174797707-2ca65f28-2972-4fe3-8e5f-a3d878d89ba2.png)

**Comment by i11info** [comment]
There is X in the right side of the search field, using color from "Primary Navbar link color". Changing that in theme settings to other than white will make it visible. Maybe some tweak need to be done on theme level, but changing "Primary Navbar link color" to light gray for example will fix this.
![searchbox](https://user-images.githubusercontent.com/22219330/176964912-3159d6ba-d642-4886-a4a4-343a202d09df.png)

**Comment by dbnschools** [comment]
LearnR is now a child theme of Boost Union. I have discontinued the development of this fork. All new releases will be as a proper child theme to Boost Union under the same name. I am closing this issue since the newest version will not have the same issues. The latest release posted here is a child theme now.
